baseURL = "/"
languageCode = 'en-us'
contentDir = "content"
enableEmoji = true
enableGitInfo = true

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    title = "Technical notes"
    languageName = "English"
    weight = 10
  [languages.cn]
    title = "技术笔记"
    languageName = "简体中文"
    contentDir = "content/zh-cn"
    weight = 20

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

 # [markup.highlight]
 #   style = "fruity"

[params]

  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"
  secondary_font  = "Inter"
  mono_font       = "Fira Code"

  [params.footer]
      copyright = "© :YEAR: Technical Labs. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
      version = true

  # [params.social]
  #     github = "lipaysamart/wiki"

  [params.docs]
    darkMode = true
    prism = true

    # gitinfo
    repoURL         = "https://github.com/lipaysamart/wiki"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
    repoBranch      = "main"                           # Name of your Git repository branch
    editPage        = true                                # enable 'Edit this page' feature - default false
    lastMod         = true                                # enable 'Last modified' date on pages - default false
    lastModRelative = true                                # format 'Last modified' time as relative - default true

    # ToC
    toc             = true                                # enable table of contents? default is true
    tocMobile       = true                                # enable table of contents in mobile view? default is true
    scrollSpy       = true                                # enable scrollspy on ToC? default is true

    # icons
    sidebarIcons    = true                                # enable sidebar icons? default false
    titleIcon       = true                                # enable front matter icon title prefix? default is false

    # content navigation
    breadcrumbs     = true                                # default is true
    navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
    navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

    listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
    backToTop       = true                                # enable back-to-top button? default true

    # front matter
    descriptions    = true                                # enable front matter descriptions under content title?

    # Link behaviour
    intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
    # extLinkNewTab   = false                             # Open external links in a new Tab? default true
    logoLinkURL     = "/"                                 # Set a custom URL destination for the top header logo link.

# [menu]
#   [[menu.primary]]
#       name  = "Docs"
#       url = "docs/"
#       identifier = "docs"
#       weight = 10
